version: 2.1

jobs:
  publish:
    parameters:
      major:
        description: Major version
        type: enum
        enum:
          - "18"
      tags:
        description: Tags to apply to this image
        type: string
        default: ""
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/image.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=oracle-xe -t oracle-xe << parameters.major >>
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/image.tar oracle-xe
      - save_cache:
          key: v1-{{ .Branch }}
          paths:
            - /caches
      - when:
          condition:
            and:
              - equal: [ master, << pipeline.git.branch >> ]
              - not:
                  equal: [ "", << parameters.tags >> ]
          steps:
            - deploy:
                name: Push application Docker image

                command: |
                  echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin

                  TAGS="<< parameters.tags >>"
                  for TAG in $TAGS; do
                    docker tag oracle-xe "${DOCKER_LOGIN}/oracle-xe:${TAG}"
                    docker push "${DOCKER_LOGIN}/oracle-xe:${TAG}"
                  done

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          major: "18"
          tags: "18 18c 18.4.0.0.0"
